### ISSUE TITLE
Section 7 Part 00_Fix_2024-01-06 (uDemy)

### ISSUE THREAD

**Issue by xrviv** [cmdruid/nostr-socket-workshop#2]
```
npm run scratch 
 
> nostr-socket@0.0.0 scratch 
> node --loader ts-node/esm --no-warnings test/scratch.ts 
 
file:///D:/Code/nostrProjects/nostr-socket-workshop/part_00/src/index.ts:47 
   const sub = this.pool.sub(this.relays, [ filter ]) 
              ^ 
TypeError: this.pool.sub is not a function at NostrSocket.sub (file:///D:/Code/nostrProjects/nostr-socket-workshop/part_00/src/index.ts:47:27) at new NostrSocket (file:///D:/Code/nostrProjects/nostr-socket-workshop/part_00/src/index.ts:39:22) at file:///D:/Code/nostrProjects/nostr-socket-workshop/part_00/test/scratch.ts:6:1 at ModuleJob.run (node:internal/modules/esm/module_job:194:25)


I checked, and there was some refactoring in pool.ts in nostr-tools which may have presented this problem.
```

Source: https://github.com/nbd-wtf/nostr-tools/commit/f56f2ae709a6e9fdc7751878c93e30d7f911ce05

**The fix:**

```
import 'websocket-polyfill';
import { Event, Filter, SimplePool } from 'nostr-tools';
import { SocketConfig, SocketOptions, socket_config } from './config.js';
import * as util from './utils.ts';
 
export class NostrSocket {
  readonly _pool: SimplePool;
  readonly filter: Filter;
  readonly relays: string[];
  readonly opt: SocketOptions;
 
  constructor(relays: string[], config?: SocketConfig) {
    this._pool = new SimplePool();
    this.relays = relays;
    this.opt = socket_config(config);
 
    this.filter = {
      kinds: [this.opt.kind],
      since: util.now()
    };
 
    // Update the subscription method
    this.subscribe(this.filter);
  }
 
  get pool(): SimplePool {
    return this._pool;
  }
 
  // Updated method to match the new API
  subscribe(filter: Filter) {
    const callbackObject = {
      onevent: (event: Event) => {
        this._eventHandler(event);
      }
    };
 
    this.pool.subscribeMany(this.relays, [filter], callbackObject);
  }
 
  _eventHandler(event: Event) {
    console.log('event:', event);
  }
}
 
export class Signer {
  readonly _secret: string;
 
  constructor(secret: string) {
    this._secret = secret;
  }
}
```

**The old code:**

```
import 'websocket-polyfill'

import {
   Event,
   Filter,
   SimplePool,
   Sub
} from 'nostr-tools'

import { 
  SocketConfig, 
  SocketOptions, 
  socket_config 
} from './config.js'

import * as util from './utils.ts'

export class NostrSocket {
  readonly _pool : SimplePool
  readonly filter : Filter
  readonly relays : string[]
  readonly opt : SocketOptions

  _sub : Sub

  constructor (
    relays : string[],
    config ?: SocketConfig
  ) {
    this._pool = new SimplePool()
 	  this.relays = relays
    this.opt = socket_config(config)
	
	  this.filter = {
	     kinds : [ this.opt.kind ],
	     since : util.now()
    }
    
    this._sub = this.sub(this.filter)
  }

  get pool () : SimplePool {
    return this._pool
  }

  sub (filter : Filter) {
    const sub = this.pool.sub(this.relays, [ filter ])
    sub.on('event', (event : Event) => {
      this._eventHandler(event)
    })
    return sub
  }

  _eventHandler (event : Event) {
      console.log('event:', event) 
  }
}

export class Signer {
  readonly _secret : string

  constructor (secret : string) {
    this._secret = secret
  }
}

```

**Comment by cmdruid** [comment]
Thank you for reporting this. Unfortunately there's significant with the new `nostr-tools` that break several parts of the code and make refactoring impossible. I went ahead and froze the version numbers on the packages, so if you re-clone the repository, everything should work properly.

Thank you for bringing this up, sorry for the trouble!
